# Generated by Django 5.1.2 on 2024-10-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('treino', 'Treino'), ('competicao', 'Competição')], default='', max_length=12)),
                ('data', models.DateField(blank=True, null=True)),
                ('distancia_percorrida', models.IntegerField(blank=True, null=True)),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('condicoes_climaticas', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
